// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/eugenshima/PriceService/internal/model"
)

// PriceServiceService is an autogenerated mock type for the PriceServiceService type
type PriceServiceService struct {
	mock.Mock
}

// GetLatestPrice provides a mock function with given fields: _a0
func (_m *PriceServiceService) GetLatestPrice(_a0 context.Context) ([]*model.Share, error) {
	ret := _m.Called(_a0)

	var r0 []*model.Share
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Share); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Share)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPriceServiceService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPriceServiceService creates a new instance of PriceServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPriceServiceService(t mockConstructorTestingTNewPriceServiceService) *PriceServiceService {
	mock := &PriceServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
